Repository qiniu/goc, pull requests merged in 2020-12, with the labels that each got.

#142 doc: update wechat image
  README.md
  docs/images/wechat.png
  go.mod
Labels: approved, size/XS

#139 fix GetAll() potentially return an unprotected map
  pkg/cover/store.go
Labels: approved, lgtm, size/XS

#143 optimize the file copy strategy of `goc build`
  pkg/build/build.go
  pkg/build/gomodules.go
  pkg/build/gomodules_test.go
  pkg/build/legacy.go
  pkg/build/legacy_test.go
  pkg/build/tmpfolder.go
  pkg/build/tmpfolder_test.go
  pkg/cover/cover.go
Labels: approved, lgtm, size/L

#145 feature: add skipFile flag for profile API
  cmd/profile.go
  docs/images/wechat.png
  pkg/cover/client_test.go
  pkg/cover/server.go
  pkg/cover/server_test.go
  tests/profile.bats
Labels: approved, lgtm, size/L

#146 Improve performance of getting filelist to copy
  pkg/build/legacy.go
  pkg/build/legacy_test.go
Labels: approved, lgtm, size/L

#150 optimize the file copy strategy of `goc build` and fix bugs
  go.mod
  go.sum
  pkg/build/build.go
  pkg/build/gomodules.go
  pkg/build/legacy.go
  pkg/build/legacy_test.go
  pkg/build/tmpfolder.go
  pkg/cover/cover_test.go
  tests/build.bats
  tests/samples/reference_other_package_project/app/main.go
  tests/samples/reference_other_package_project/foo/foo.go
  tests/samples/reference_other_package_project/go.mod
Labels: approved, lgtm, size/L
