Repository qiniu/goc, pull requests merged in 2020-09, with the labels that each got.

#99 vscode extension init
  .gitignore
  tools/vscode-ext/.gitignore
  tools/vscode-ext/.vscode/extensions.json
  tools/vscode-ext/.vscode/launch.json
  tools/vscode-ext/.vscode/settings.json
  tools/vscode-ext/.vscode/tasks.json
  tools/vscode-ext/.vscodeignore
  tools/vscode-ext/CHANGELOG.md
  tools/vscode-ext/README.md
  tools/vscode-ext/package-lock.json
  tools/vscode-ext/package.json
  tools/vscode-ext/src/extension.ts
  tools/vscode-ext/src/gocserver.ts
  tools/vscode-ext/src/test/runTest.ts
  tools/vscode-ext/src/test/suite/extension.test.ts
  tools/vscode-ext/src/test/suite/index.ts
  tools/vscode-ext/tsconfig.json
  tools/vscode-ext/tslint.json
  tools/vscode-ext/vsc-extension-quickstart.md
Labels: approved, lgtm, size/XXL

#105 Add chinese readme & vscode gif
  README.md
  README_zh.md
  docs/images/goc-vscode.gif
  docs/images/wechat.png
Labels: approved, lgtm, size/L

#104 goc profile: add coverfile flag
  cmd/diff_test.go
  cmd/profile.go
  pkg/cover/client.go
  pkg/cover/client_test.go
  pkg/cover/server.go
  pkg/cover/server_test.go
  tests/profile.bats
  tests/samples/run_for_several_seconds/a/a.go
  tests/samples/run_for_several_seconds/b/b.go
  tests/samples/run_for_several_seconds/main.go
Labels: approved, lgtm, size/L

#111 update wechat group image
  docs/images/wechat.png
Labels: approved, size/XS

#114 Fix windows filepath incompatible issue
  tools/vscode-ext/README.md
  tools/vscode-ext/package-lock.json
  tools/vscode-ext/package.json
  tools/vscode-ext/src/gocserver.ts
Labels: approved, lgtm, size/L

#112 Clear coverage by service&addr
  .github/workflows/e2e_test_check.yml
  .github/workflows/style_check.yml
  .github/workflows/ut_check.yml
  cmd/clear.go
  pkg/cover/client.go
  pkg/cover/client_test.go
  pkg/cover/server.go
  pkg/cover/server_test.go
  tests/clear.bats
Labels: approved, lgtm, size/L

#110 Error returned when no profiles fetched
  cmd/profile.go
  pkg/cover/client_test.go
  pkg/cover/server.go
  tests/profile.bats
  tests/server.bats
Labels: approved, lgtm, size/M

#120 Support configuring the persistence file path
  cmd/register.go
  cmd/run.go
  cmd/server.go
  go.mod
  go.sum
  pkg/cover/client.go
  pkg/cover/client_test.go
  pkg/cover/server.go
  pkg/cover/server_test.go
  pkg/cover/store.go
  pkg/cover/store_test.go
  tests/server.bats
Labels: approved, lgtm, size/L
