Repository qiniu/goc, pull requests merged in 2020-08, with the labels that each got.

#90 Fix cover service listen port issue for #74
  pkg/cover/instrument.go
  tests/agent.bats
  tests/run-ci-actions.sh
  tests/samples/simple_agent/go.mod
  tests/samples/simple_agent/main.go
Labels: approved, lgtm, size/L

#91 add merge command
  cmd/merge.go
  cmd/merge_test.go
  pkg/cover/client.go
  tests/merge.bats
  tests/run-ci-actions.sh
  tests/samples/merge_profile_samples/a.voc
  tests/samples/merge_profile_samples/b.voc
  tests/samples/merge_profile_samples/c.voc
  tests/samples/merge_profile_samples/empty.voc
  tests/samples/merge_profile_samples/overlap.voc
  tests/samples/merge_profile_samples/setmode.voc
Labels: approved, lgtm, size/L

#95 add support for go.mod contains replace directive
  go.mod
  go.sum
  pkg/build/build.go
  pkg/build/gomodules.go
  pkg/build/gomodules_test.go
  pkg/build/tmpfolder.go
  tests/build.bats
  tests/samples/gomod_replace_library/bar.go
  tests/samples/gomod_replace_library/go.mod
  tests/samples/gomod_replace_project/go.mod
  tests/samples/gomod_replace_project/main.go
  tests/samples/gomod_samples/a/go.mod
  tests/samples/gomod_samples/b/go.mod
Labels: approved, lgtm, size/L

#96 fix golint error
  cmd/merge_test.go
  tests/samples/gomod_replace_library/bar.go
Labels: approved, lgtm, size/XS

#97 lint: only check for Pull request
  .github/workflows/golangci-lint.yml
Labels: approved, lgtm, size/XS

#98 add tips for goc merge
  README.md
Labels: approved, lgtm, size/XS

#85 Errors will show in command instead of output files when get a profile
  pkg/cover/client.go
  pkg/cover/client_test.go
Labels: approved, lgtm, size/M
