Repository qiniu/goc, pull requests merged in 2020-06, with the labels that each got.

#20 goc add diff cmd
  .github/workflows/ut_check.yml
  cmd/diff.go
  cmd/diff_test.go
  go.mod
  go.sum
  pkg/cover/cover.go
  pkg/cover/cover_test.go
  pkg/cover/delta.go
  pkg/cover/delta_test.go
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/prow/job.go
  pkg/prow/job_test.go
  pkg/qiniu/client.go
  pkg/qiniu/client_test.go
  pkg/qiniu/mock.go
  pkg/qiniu/object.go
  pkg/qiniu/qnPresubmit.go
  pkg/qiniu/qnPresubmit_test.go
Labels: approved, lgtm, size/XXL

#28 Update command usage
  cmd/build.go
  cmd/install.go
Labels: approved, lgtm, size/M

#32 add new command 'goc init'
  cmd/init.go
  pkg/build/legacy.go
  pkg/build/tmpfolder.go
  pkg/cover/store.go
Labels: approved, size/M

#31 do retry when connecting github failed
  cmd/build.go
  cmd/diff.go
  go.mod
  go.sum
  pkg/github/github.go
Labels: approved, lgtm, size/S

#35 refactor install/build command
  cmd/build.go
  cmd/clear.go
  cmd/commonflags.go
  cmd/cover.go
  cmd/init.go
  cmd/install.go
  cmd/profile.go
  cmd/root.go
  go.mod
  go.sum
  pkg/build/binarymove.go
  pkg/build/build.go
  pkg/build/gomodules.go
  pkg/build/install.go
  pkg/build/legacy.go
  pkg/build/tmpfolder.go
  pkg/build/tmpfolder_test.go
  pkg/cover/cover.go
  pkg/cover/cover_test.go
  pkg/cover/server.go
  pkg/cover/store.go
  pkg/qiniu/qnPresubmit.go
  tests/e2e/simple_project_test.go
  tests/samples/simple_gopath_project/go.mod
Labels: approved, lgtm, size/XL

#37 Feature: add goc run command
  cmd/build.go
  cmd/commonflags.go
  cmd/cover.go
  cmd/install.go
  cmd/run.go
  pkg/build/build.go
  pkg/build/gomodules.go
  pkg/build/install.go
  pkg/build/legacy.go
  pkg/build/tmpfolder.go
  pkg/cover/cover.go
  pkg/cover/cover_test.go
  pkg/cover/instrument.go
  pkg/cover/server.go
  pkg/cover/store.go
  pkg/cover/store_test.go
Labels: approved, lgtm, size/XL

#39 fix #14
  cmd/build.go
  cmd/build_test.go
  cmd/install.go
  cmd/install_test.go
  cmd/run.go
  pkg/build/build.go
  pkg/build/build_test.go
  pkg/build/errors.go
  pkg/build/gomodules.go
  pkg/build/install.go
  pkg/build/install_test.go
  pkg/build/legacy.go
  pkg/build/tmpfolder.go
  pkg/build/tmpfolder_test.go
  tests/e2e/simple_project_test.go
  tests/run-ci-actions.sh
Labels: approved, lgtm, size/XL

#42 Enhance error handling
  cmd/build.go
  cmd/build_test.go
  cmd/commonflags.go
  cmd/install.go
  cmd/install_test.go
  cmd/list.go
  cmd/root.go
  cmd/run.go
  pkg/build/build.go
  pkg/build/build_test.go
  pkg/build/errors.go
  pkg/build/install.go
  pkg/build/install_test.go
  pkg/build/legacy.go
  pkg/build/run.go
  pkg/build/tmpfolder.go
  pkg/build/tmpfolder_test.go
  pkg/cover/cover.go
  pkg/cover/cover_test.go
Labels: approved, lgtm, size/L

#40 README.md: Add demo gif of goc run
  README.md
  docs/images/intro.gif
Labels: approved, lgtm, size/XS

#44 do not print host for goc agent by default
  README.md
  pkg/cover/instrument.go
Labels: approved, lgtm, size/S

#45 doc: fix typo
  README.md
  pkg/cover/instrument.go
  tests/e2e/simple_project_test.go
Labels: approved, size/XS

#46 Add release Action
  .github/workflows/release.yml
  ci-build.sh
Labels: approved, lgtm, size/M

#47 doc: be consistent and remove noise
  cmd/build.go
  cmd/commonflags.go
  cmd/install.go
  cmd/run.go
  pkg/github/github.go
Labels: approved, size/S

#49 goc build: provide short flag for output option
  cmd/build.go
Labels: approved, lgtm, size/XS
