Repository qiniu/goc, pull requests merged in 2020-07, with the labels that each got.

#55 goc version managment
  ci-build.sh
  cmd/version.go
  go.mod
Labels: approved, lgtm, size/M

#56 badge: add release badge
  README.md
Labels: approved, lgtm, size/XS

#58 support for new packages that need downloading.
  pkg/cover/cover.go
Labels: approved, lgtm, size/XS

#54 Add particular port for registered service when goc build
  cmd/build.go
  cmd/commonflags.go
  cmd/cover.go
  cmd/install.go
  cmd/run.go
  pkg/cover/cover.go
  pkg/cover/cover_test.go
  pkg/cover/instrument.go
Labels: approved, lgtm, size/S

#59 auto version
  cmd/version.go
Labels: approved, size/S

#60 support goc version using `go get`
  cmd/version.go
Labels: approved, lgtm, size/S

#62 doc: add Tips into readme
  README.md
  cmd/commonflags.go
Labels: approved, size/S

#63 Add agentport flag check
  .gitignore
  cmd/build.go
  cmd/commonflags.go
  cmd/commonflags_test.go
  cmd/cover.go
  cmd/install.go
  cmd/run.go
  pkg/cover/cover.go
Labels: approved, lgtm, size/L

#68 fix wrong output binary name
  Makefile
  cmd/build_test.go
  pkg/build/build.go
  pkg/cover/cover_test.go
  tests/samples/simple_project2/go.mod
  tests/samples/simple_project2/main.go
  tests/samples/simple_project_with_internal/go.mod
  tests/samples/simple_project_with_internal/internal/foo.go
  tests/samples/simple_project_with_internal/main.go
Labels: approved, lgtm, size/L

#69 goc build/test goc
  .github/workflows/e2e_test_check.yml
  .github/workflows/ut_check.yml
  codecov.yaml
  go.mod
  go.sum
  pkg/build/build.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/simple_project_test.go
  tests/run-ci-actions.sh
  tests/server.bats
Labels: approved, lgtm, size/L

#67 cmd profile support get by name or address list
  cmd/profile.go
  go.mod
  go.sum
  pkg/cover/client.go
  pkg/cover/client_test.go
  pkg/cover/instrument.go
  pkg/cover/server.go
  pkg/cover/server_test.go
Labels: approved, lgtm, size/L

#76 optimize statement and encapsulate logic of #67
  cmd/profile.go
  pkg/cover/client.go
  pkg/cover/client_test.go
  pkg/cover/server.go
  pkg/cover/server_test.go
Labels: approved, lgtm, size/L

#77 Enhance "file lock sync" logic
  pkg/build/build.go
  tests/README.md
  tests/build.bats
  tests/clear.bats
  tests/cover.bats
  tests/diff.bats
  tests/init.bats
  tests/install.bats
  tests/list.bats
  tests/profile.bats
  tests/register.bats
  tests/run.bats
  tests/util.sh
  tests/version.bats
Labels: approved, lgtm, size/L

#79 make profile flag description clearer
  cmd/profile.go
Labels: approved, lgtm, size/XS

#82 fix golint error and add golanglint-ci to check code quality persistently
  .github/workflows/golangci-lint.yml
  README.md
  cmd/build_test.go
  cmd/commonflags.go
  cmd/install_test.go
  pkg/build/build.go
  pkg/build/build_test.go
  pkg/build/errors.go
  pkg/build/install.go
  pkg/build/tmpfolder.go
  pkg/build/tmpfolder_test.go
  pkg/cover/cover.go
  pkg/cover/cover_test.go
  pkg/cover/server.go
  pkg/github/github.go
  pkg/prow/job.go
  pkg/qiniu/mock.go
  pkg/qiniu/object.go
  pkg/qiniu/qnPresubmit.go
Labels: approved, size/L

#86 README: clarify the go version for goc developing
  README.md
Labels: approved, lgtm, size/XS

#81 Add test case for goc diff
  cmd/diff.go
  pkg/cover/cover_test.go
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/prow/job.go
  pkg/prow/job_test.go
  pkg/qiniu/client.go
  pkg/qiniu/mock.go
  pkg/qiniu/object.go
  pkg/qiniu/object_test.go
  pkg/qiniu/qnPresubmit.go
  pkg/qiniu/qnPresubmit_test.go
Labels: approved, lgtm, size/XL

#87 Fix golint and ineffassign
  go.mod
  go.sum
  pkg/build/tmpfolder.go
  pkg/build/tmpfolder_test.go
  pkg/cover/client_test.go
  pkg/cover/delta.go
  pkg/github/github.go
  pkg/github/github_test.go
  pkg/prow/job.go
  pkg/qiniu/client.go
  pkg/qiniu/mock.go
  pkg/qiniu/object_test.go
  tests/samples/multi_mains_project_with_internal/foo/bar1.go
  tests/samples/multi_mains_project_with_internal/foo/bar2.go
  tests/samples/multi_mains_project_with_internal/foo/internal/qiniu/xiaoda.go
  tests/samples/multi_mains_project_with_internal/foo/internal/xiaoming.go
  tests/samples/multi_mains_project_with_internal/internal/foo.go
  tests/samples/simple_gopath_project/src/qiniu.com/simple_gopath_project/modulea/foo.go
  tests/samples/simple_project_with_internal/foo/bar1.go
  tests/samples/simple_project_with_internal/foo/bar2.go
  tests/samples/simple_project_with_internal/foo/internal/qiniu/xiaoda.go
  tests/samples/simple_project_with_internal/foo/internal/xiaoming.go
  tests/samples/simple_project_with_internal/internal/foo.go
Labels: approved, lgtm, size/M

#88 Fix misspell
  pkg/prow/job_test.go
Labels: approved, lgtm, size/XS
