Repository qiniu/goc, pull requests merged in 2020-10, with the labels that each got.

#125 doc: update wechat group image
  docs/images/wechat.png
Labels: approved, size/XS

#115 Add remove command
  cmd/remove.go
  docs/images/wechat.png
  pkg/cover/client.go
  pkg/cover/client_test.go
  pkg/cover/server.go
  pkg/cover/server_test.go
  pkg/cover/store.go
  pkg/cover/store_test.go
  tests/remove.bats
  tests/run-ci-actions.sh
Labels: approved, lgtm, size/L

#124 Do cover in another way
  cmd/build.go
  cmd/build_test.go
  cmd/cover.go
  cmd/install.go
  cmd/run.go
  pkg/build/build.go
  pkg/build/tmpfolder.go
  pkg/cover/cover.go
  pkg/cover/cover_test.go
  pkg/cover/instrument.go
  pkg/cover/internal/tool/cover.go
  pkg/cover/internal/tool/edit.go
  tests/build.bats
  tests/samples/complex_project/go.mod
  tests/samples/complex_project/main.go
Labels: approved, lgtm, size/XXL
