Repository qiniu/goc, pull requests merged in 2020-05, with the labels that each got.

#1 Update License
  LICENSE
Labels: size/L

#2 init the directory structure and create OWNERS file
  .gitignore
  OWNERS
  cmd/goc/app/root.go
  cmd/goc/app/server.go
  cmd/goc/goc.go
  go.mod
  go.sum
Labels: lgtm, size/L

#3 init draf README
  README.md
Labels: approved, lgtm, size/XS

#5 add github action ci check
  .github/workflows/style_check.yml
  .github/workflows/ut_check.yml
  cmd/goc/app/root.go
  cmd/goc/app/server.go
Labels: approved, lgtm, size/M

#4 add coverage server
  .gitignore
  README.md
  cmd/goc/app/server.go
  go.mod
  go.sum
  pkg/cover/server.go
  pkg/cover/store.go
  pkg/cover/store_test.go
  pkg/cover/worker.go
Labels: approved, lgtm, size/XXL

#7 optimize ci check job name
  .github/workflows/style_check.yml
  .github/workflows/ut_check.yml
  README.md
Labels: approved, lgtm, size/S

#8 Migrate qbox/goc to qiniu/goc
  .github/workflows/e2e_test_check.yml
  .github/workflows/style_check.yml
  .github/workflows/ut_check.yml
  README.md
  cmd/goc/app/build.go
  cmd/goc/app/cover.go
  cmd/goc/app/install.go
  go.mod
  go.sum
  pkg/build/binarymove.go
  pkg/build/gomodules.go
  pkg/build/legacy.go
  pkg/build/tmpfolder.go
  pkg/build/tmpfolder_test.go
  pkg/cover/cover.go
  pkg/cover/cover_test.go
  pkg/cover/delta.go
  pkg/cover/instrument.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/simple_project_test.go
  tests/run-ci-actions.sh
  tests/samples/simple_gopath_project/go.mod
  tests/samples/simple_gopath_project/src/qiniu.com/simple_gopath_project/main.go
  tests/samples/simple_project/go.mod
  tests/samples/simple_project/main.go
Labels: approved, lgtm, size/XXL

#10 adjust project directory structure to be more friendly to use
  .github/workflows/e2e_test_check.yml
  .gitignore
  README.md
  cmd/build.go
  cmd/cover.go
  cmd/install.go
  cmd/root.go
  cmd/server.go
  go.sum
  goc.go
Labels: approved, lgtm, size/M

#11 add goc profile command
  .gitignore
  cmd/cover.go
  cmd/profile.go
  cmd/server.go
  pkg/cover/client.go
Labels: approved, lgtm, size/M

#12 upload coverage report to codecov
  .github/workflows/ut_check.yml
  README.md
Labels: approved, size/XS

#13 add goreport and godoc badge into README doc
  README.md
Labels: approved, size/XS

#15 add example into README document
  README.md
  go.sum
Labels: approved, size/M

#16 fix typo
  README.md
Labels: approved

#21 update copyright with qiniu.com url
  LICENSE
  cmd/build.go
  cmd/cover.go
  cmd/install.go
  cmd/profile.go
  cmd/root.go
  cmd/server.go
  goc.go
  pkg/build/binarymove.go
  pkg/build/gomodules.go
  pkg/build/legacy.go
  pkg/build/tmpfolder.go
  pkg/build/tmpfolder_test.go
  pkg/cover/client.go
  pkg/cover/cover.go
  pkg/cover/cover_test.go
  pkg/cover/delta.go
  pkg/cover/instrument.go
  pkg/cover/server.go
  pkg/cover/store.go
  pkg/cover/store_test.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/simple_project_test.go
  tests/samples/simple_gopath_project/src/qiniu.com/simple_gopath_project/main.go
  tests/samples/simple_project/main.go
Labels: approved, size/M

#22 remove copyright leader for test sample file
  tests/samples/simple_gopath_project/src/qiniu.com/simple_gopath_project/main.go
  tests/samples/simple_project/main.go
Labels: approved, lgtm, size/M

#23 Add coverage clear feature
  cmd/clear.go
  cmd/cover.go
  pkg/cover/client.go
  pkg/cover/cover.go
  pkg/cover/cover_test.go
  pkg/cover/instrument.go
  pkg/cover/server.go
Labels: approved, lgtm, size/L

#25 Add usage for some commands
  cmd/clear.go
  cmd/cover.go
  cmd/profile.go
  cmd/root.go
  cmd/server.go
Labels: approved, lgtm, size/M

#27 doc: the feature about clearing code coverage counters is supported now
  README.md
Labels: approved, size/XS
