Repository qiniu/goc, pull requests merged in 2021-09, with the labels that each got.

#224 重构
  cmd/build.go
  cmd/install.go
  cmd/list.go
  cmd/profile.go
  cmd/root.go
  cmd/server.go
  cmd/watch.go
  pkg/build/agent.tpl
  pkg/build/agentwatch.tpl
  pkg/build/build.go
  pkg/build/build_flags.go
  pkg/build/config.go
  pkg/build/cover.go
  pkg/build/goenv.go
  pkg/build/inject.go
  pkg/build/install.go
  pkg/build/internal/tool/cover.go
  pkg/build/internal/tool/edit.go
  pkg/build/internal/websocket/websocket.tar
  pkg/build/internal/websocket/wsdep.go
  pkg/build/template.go
  pkg/build/tmpfolder.go
  pkg/cover/cover.go
  pkg/flag/build_flags.go
  pkg/flag/flags.go
  pkg/flag/help.go
  pkg/flag/packages.go
  pkg/log/log.go
  pkg/watch/watch.go
Labels: approved, size/XXL

#225 update license
  cmd/build.go
  cmd/install.go
  cmd/list.go
  cmd/merge.go
  cmd/profile.go
  cmd/root.go
  cmd/server.go
  cmd/version.go
  cmd/watch.go
  main.go
  pkg/build/agent.tpl
  pkg/build/agentwatch.tpl
  pkg/build/build.go
  pkg/build/build_flags.go
  pkg/build/config.go
  pkg/build/cover.go
  pkg/build/goenv.go
  pkg/build/inject.go
  pkg/build/install.go
  pkg/build/internal/websocket/wsdep.go
  pkg/build/template.go
  pkg/build/tmpfolder.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/log/ci_logger.go
  pkg/log/display.go
  pkg/log/loading_text.go
  pkg/log/log.go
  pkg/log/logger.go
  pkg/log/terminal.go
  pkg/log/terminal_logger.go
  pkg/server/api.go
  pkg/server/common.go
  pkg/server/rpcstream.go
  pkg/server/server.go
  pkg/server/util.go
  pkg/server/watchstream.go
  pkg/watch/watch.go
  tests/e2e/cmd.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/e2e_test.go
  tests/e2e/samples_mgr.go
Labels: approved, size/XL

#228 fixed: optimize the local operation mode and add custom agentport and center server
  cmd/run.go
Labels: approved, size/S

#232 add windows release
  .github/workflows/release.yml
Labels: approved, size/S

#233 📃 docs: update doc
  cmd/merge.go
  cmd/profile.go
  cmd/server.go
  cmd/service.go
  doc/protocol.md
Labels: approved, size/M

#234 🐞 fix: rm only specific id in store
  pkg/server/api.go
Labels: approved, size/S
