Repository qiniu/goc, pull requests merged in 2021-02, with the labels that each got.

#164 doc: update wechat image
  docs/images/wechat.png
Labels: approved

#163 fix issue #162
  pkg/cover/instrument.go
Labels: approved, lgtm, size/M

#165 feat(profile): add create dir function to output flag
  cmd/profile.go
Labels: approved, lgtm, size/S

#167 add go 1.16 in CI check
  .github/workflows/e2e_test_check.yml
  .github/workflows/ut_check.yml
Labels: approved, lgtm, size/XS

#168 Update copy to v1.4.2
  go.mod
  go.sum
Labels: approved, lgtm, size/XS

#170 doc: update wechat image
  README_zh.md
  docs/images/wechat.png
Labels: approved, size/XS
