Repository qiniu/goc, pull requests merged in 2021-07, with the labels that each got.

#200 doc: update wechat image
  docs/images/wechat.png
Labels: approved, size/XS

#198 add command goc list
  cmd/list.go
  go.mod
  go.sum
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/cover/agent.tpl
  pkg/cover/agentwatch.tpl
Labels: size/L

#203 增加 install 的 help
  README.md
  cmd/build.go
  cmd/install.go
  cmd/root.go
  doc/goc_diff.drawio
  doc/protocol.drawio
  pkg/build/build.go
  pkg/build/install.go
  pkg/flag/build_flags.go
Labels: approved, size/L

#206 add release ci & add version cmd
  .github/workflows/e2e-linux.yml
  .github/workflows/e2e-wins.yml
  .github/workflows/release.yml
  cmd/version.go
  hack/release.sh
Labels: approved, size/L

#207 add e2e test & ci
  .github/workflows/e2e-linux.yml
  .github/workflows/e2e-wins.yml
  .gitignore
  Makefile
  go.mod
  go.sum
  pkg/build/goenv.go
  pkg/build/tmpfolder.go
  tests/README.md
  tests/e2e/cmd.go
  tests/e2e/e2e_suite_test.go
  tests/e2e/e2e_test.go
  tests/e2e/samples/basic-project/go.mod
  tests/e2e/samples/basic-project/main.go
  tests/e2e/samples/go.mod
  tests/e2e/samples/meta.yaml
  tests/e2e/samples_mgr.go
Labels: approved, size/L

#208 add readme for e2e test
  doc/things_about_e2e_test.md
  tests/README.md
  tests/e2e/cmd.go
  tests/e2e/e2e_test.go
Labels: approved, size/M

#205 add basic goc profile
  cmd/profile.go
  pkg/client/client.go
  pkg/client/client_test.go
Labels: size/L

#209 update e2e test of goc profile
  tests/README.md
  tests/e2e/cmd.go
  tests/e2e/e2e_test.go
  tests/e2e/samples/basic4ever-project/go.mod
  tests/e2e/samples/basic4ever-project/main.go
  tests/e2e/samples/meta.yaml
Labels: approved, size/M

#210 get next abailable port for e2e test
  go.mod
  go.sum
  tests/e2e/samples_mgr.go
Labels: approved, size/M
