Repository qiniu/goc, pull requests merged in 2021-08, with the labels that each got.

#212 vulnerability fix: upgrade gin from v1.6.3 to v1.7.2
  go.mod
  go.sum
Labels: lgtm, approved, size/M

#213 doc: provide one command to install goc
  README.md
  README_zh.md
Labels: lgtm, approved, size/S

#216 some fixs
  .github/workflows/release.yml
  cmd/merge.go
  pkg/build/goenv.go
  pkg/cover/agentwatch.tpl
  pkg/cover/internal/tool/cover.go
  pkg/flag/build_flags.go
Labels: approved, size/M

#218 doc: update wechat image
  docs/images/wechat.png
Labels: size/XS, approved

#219 Update README_zh.md
  README_zh.md
Labels: lgtm, size/XS, approved
